function phidot = phidotfun(in1,r_c,P)
%PHIDOTFUN
%    PHIDOT = PHIDOTFUN(IN1,R_C,P)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Jul-2020 16:24:35

o = in1(:,5);
u = in1(:,3);
v = in1(:,4);
w = in1(:,6);
x = in1(:,1);
y = in1(:,2);
t2 = cos(o);
t3 = sin(o);
t6 = -x;
t4 = r_c.*t2;
t5 = r_c.*t3;
t7 = -t5;
t9 = P+t4+t6;
t8 = t7+y;
phidot = w-((u+t5.*w).*(t5-y)-t9.*(v-t4.*w))./((t5-y).^2+t9.^2);
