function out1 = phidot_ldot_fun(in1,r_c,P)
%PHIDOT_LDOT_FUN
%    OUT1 = PHIDOT_LDOT_FUN(IN1,R_C,P)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    31-Jul-2020 10:47:39

o = in1(:,5);
u = in1(:,3);
v = in1(:,4);
w = in1(:,6);
x = in1(:,1);
y = in1(:,2);
t2 = cos(o);
t3 = sin(o);
t6 = -x;
t4 = r_c.*t2;
t5 = r_c.*t3;
t7 = t4.*w;
t8 = t5.*w;
t9 = -t5;
t14 = P+t4+t6;
t15 = (t5-y).^2;
t10 = -t7;
t11 = t8+u;
t12 = t9+y;
t16 = t14.^2;
t13 = t10+v;
t17 = t15+t16;
out1 = [w-(t14.*(t7-v)+t11.*(t5-y))./t17,-1.0./sqrt(t17).*(t11.*t14-(t7-v).*(t5-y))];
